sudo: false
language: node_js
node_js:
  - 'iojs'
  - '0.12'
  - '0.10'
before_script:
  - 'npm install -g bower grunt-cli'
  - 'npm install -g jasmine-core'
  - 'npm install -g phantomjs-prebuilt'
  - 'bower install'
